###########
# site.url, site.title

title: "Goren Lab"

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: ""
url:  "http://goren-lab.github.io"
description: "Goren Lab website UCSD"

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

